coverage:
  status:
    project:
      default:
        # basic
        target: 70
        threshold: null
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
  notify:
    slack:
      default:
        url: secret:FlB0auxDj3BTDrUaGXWSPUcQ7JZ5IJibDwaPxxm4LeLK4qoVk6fttLZiACwfMJUs9Yi2qxIXPOpi6sukkAid8qJzgMo/LTXXHzrFxu9Du/99R1Kl3clfeXqdcaARWb+7xawOwei9MXQU6FzlShFSpHNxaYfLC4o89ZMWs5ael+E=
        threshold: 1%
